### ISSUE TITLE
AssertionError: No data selected for False

### ISSUE THREAD

**Issue by ghost** [snikolov/neural-beats#19]
I'm getting stuck at this point, any help would be great!

```
Using TensorFlow backend.
Loaded 1/1 directories
Traceback (most recent call last):
  File "lstm_model.py", line 388, in <module>
    run_train()
  File "lstm_model.py", line 297, in run_train
    config_sequences, train_generator, valid_generator = prepare_data()
  File "lstm_model.py", line 142, in prepare_data
    validation_percent=VALIDATION_PERCENT)
  File "./data.py", line 62, in __init__
    assert len(self.data_indices) > 0, 'No data selected for {}'.format(is_validation)
AssertionError: No data selected for False
```

**Comment by snikolov** [comment]
Hello, what data are you pointing your script to?

I have not included the data I used, as it is unfortunately not licensed
for sharing in open source software. I got my data (midi drum loops) from
GrooveMonkee. They have free packs so you could download some example data.
I have not tested extensively on other midi data.

**Comment by snikolov** [comment]
Ah, just saw your issue on the magenta repo :-) So it looks like you have
some midi data, but neither magenta nor neural beats is able to process it?
If you send a sample midi file, that might help to identify the problem.

**Comment by ghost** [comment]
I pointed the script to a new data folder. It's a strange issue with the midi because some files that have drums on channel 10 work while others don't and nothing from Ableton seems to work even when converted to ch10. [Here's a link](https://drive.google.com/open?id=1VLFcwlj7CUwVjMgkxovwEonoF1wVgrBs) to some of the midi I've been using with sample files from each of the types I described. 

With the update in Magenta there's a description now that mentions why files were rejected, it looks like some are too short or too long but I'm still having the same issue for files that should be working.

Thanks for the help!!
